### ISSUE TITLE
Process MortalityInstantaneous. fisheries table enhancement

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#114]
In the table fisheries. allow there to be multiple categories and selectivity labels for a single row.
this will mean changing the name from category -> categories and the same for selectivities

**Comment by Craig44** [comment]
line 177 MortalityInstantaneous.cpp

**Comment by Craig44** [comment]
[CurrentComplex.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1345914/CurrentComplex.zip)

In CurrentComplex is the current structure that we are forced to have. But we need to allow short hand syntax in the categories table. As is demonstrated in WhatWeWantComplex.zip
[WhatWeWantComplex.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1345918/WhatWeWantComplex.zip)

**Comment by Zaita** [comment]
Done. Please confirm and close ticket @Craig44 

Note: The WhatWeWant will need to add format= to your table or sex= etc.

**Comment by Zaita** [comment]
@Craig44 Confirmed?
