### ISSUE TITLE
Shift base weight unit from Kgs to tonnes

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#115]
Do you agree with this? @alistairdunn1

**Comment by alistairdunn1** [comment]
More detail required. Catches are currently in tonnes, and length weight relationships should be specified to convert length in cm to weight in tonnes.

**Comment by Craig44** [comment]
ADD a @model command fro units 
@model
units = tonnes

**Comment by Craig44** [comment]
proposed structure
@model
base_weight_units "tonnes"

@age_length
units kgs/tonnes will need to be tweaked based on the base weight

**Comment by Zaita** [comment]
Removed units from the model. All units will be whatever space the user has in their configuration file.

**Comment by Craig44** [comment]
I think this issue needs to be addressed again. There currently exists a base unit for weights which is  kgs. We allow users to specify different length_weight parameter unit space (i.e. parameter a and b can be specified as grammes, kgs or tonnes). Depending on which unit the user defines for this CASAL2 will convert the mean weight at length to kgs. We have also allowed users to give units for any weight unit given to the model. All this does is convert the values given to kgs. Why this is an issue is because Casal2 converts the parameter to kgs in the dobuild(). But if the user wants to estimate these values they think the parameter is in tonnes (for example B0) but Casal2 is actually handling it as kgs which then throws the bounds and other @estimate statemetns into chaos. @alistairdunn1  I am going to suggest again to have a base_weight subcommand in the @model block as this in my mind is the best solution. let me know what you think. Chairs

**Comment by Craig44** [comment]
base_weight_units sub command added to the @model block
