### ISSUE TITLE
Check table fisheries column names

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#127]
Above line 126 InstantaneousMortality.cpp  we need to check if the column labels are expected.

**Comment by Zaita** [comment]
Please comment with business logic. What columns should exist etc

**Comment by Craig44** [comment]
One column label must contain year else error out. also if check that the labels are check line 97  InstantaneousMortality.cpp.

Check that the remaining columns are the same as the labels given in the method column in the methods_table
