### ISSUE TITLE
Jenkins Build System

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#134]
The windows/Documnetation and installer build says it has not successfully built for 20 days, but is not failing either. This needs to be looked into.

**Comment by Zaita** [comment]
Please comment with business logic. What columns should exist etc

**Comment by Zaita** [comment]
The documentation update done on the first failing build isn't working with the newer version of miktek on the build system. Recommend you upgrade your local copy and fix issue (for me it was related to caption.sty not being found)

**Comment by Craig44** [comment]
Linux/Documentation builder broken. Can we try delete the second documentation folder that has turned up and see if that is a factor for the broken build

**Comment by Zaita** [comment]
I've wiped out the workspace and kicked off a build. If it fails now then the issue still exists with some changes that were made when moving the documentation to the GettingStarted etc. Somewhere in your files you're referencing "documentation" instead of "Documentation". Linux is case-sensitive
