### ISSUE TITLE
Spec for estimation_phase 

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#137]
What does the input parameter  "estimation_phase" in Estimate.cpp do I can't see it appearing in the code base and has "TBA" definition can anyone clarify it for me. Thanks @Zaita  @alistairdunn1

**Comment by Craig44** [comment]
If no one replies within a week I am going to remove this variable from the constructor as it is confusing in the manual and I cannot see functionality in the code. @alistairdunn1  @Zaita

**Comment by smormede** [comment]
Below, taken from spm manual. Will probably break if you remove it. The aim is that if you have a parameter of lesser importance you estimate it in estimation phase two so it doesn’t have such an impact on the space in which the model is trying to estimate its parameter.

I say keep it.

Sophie



estimation phase Phase at which this parameter should be estimated, in point estimation
Type: Integer
Default: 1
Value: Defines the phase at which this parameter should be freed

**Comment by Craig44** [comment]
Okay. Did you implement it @Zaita  in SPM? if so it may be quicker for you to look at if not I will look into it over the coming weeks to spec it.

**Comment by Zaita** [comment]
I did not.

**Comment by alistairdunn1** [comment]
Yep, keep it - The implementation may be a bit tricky, as we need to call the minimiser once for each phase, while holding some variables constant.

**Comment by Craig44** [comment]
@Zaita  I have been writing out how we may want to implement this functionality. I am thinking that this can be handled in the function RunEstimation() in model.cpp. I have attached pseudo code. Can you have a look and see what you think
Chairs
[estimate_phase_spec.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/360691/estimate_phase_spec.txt)

**Comment by Zaita** [comment]
Done. Implemented with --phases command line parameter
