### ISSUE TITLE
report type=simulated_observation

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#138]
I am trying to report three simulated sets of @observations blocks to the same file. And if I run 3 simulations using the command casal2 -s 3. I want 3 separate files each file containing the three sets of simulated observations.

Casal2 generates 3 files fine. for example if the subcommand file_name = sim_obs, with the command casal2 -s 3 it will produce sim_obs.1, sim_obs.2, sim_obs.3. But the observations within each file is not always as expected. For example in the run I did I have attached the all the necessary files from the following command

casal2 -s 3

I expect each sim_obs file to contain 3 observations but the first two don't and the last one doesn't. The zip file contains all files needed to replicate the case plus output from my run. I have added the log file that I printed as well. It looks to me like a the model begins the next simulation run before it can finish printing the report from the previous simulation. 

In log1.out line 7 it has entered the second simulation loop but in line 8 the report.cpp is printing to a file with the suffix .1

[sim_obs.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/327044/sim_obs.zip)

**Comment by Craig44** [comment]
I believe it is a threading (Report managing) issue in this issue. It looks like the simulation loop (Model.cpp line 592) is iterating before the report has finished flushing the reports? What is the best way to pause the loop for a report to finish before the next simulation?

**Comment by Zaita** [comment]
This isn't actually a bug. But you should put a check in the reports manager to ensure no two reports share the same file_name. This is because you cannot guarantee the order reports will be printed in. So in this case the overwrite is being done after one of the appends.

The fix will need discussion.

**Comment by Craig44** [comment]
Even when I pipe each report block to a new file, the situation still occurs.check out the zipped file. And since they each have their own report I have made writemode = overwrite

[sim_report.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/330881/sim_report.zip)
