### ISSUE TITLE
Minimiser type=cppad

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#139]
I have received the following error message that a NIWA user got. They are executing Casal2 on a windows 7 (typical NIWA setup)

Context he was estimating the same model with different minimisers. betadiff and gammadiff worked fine but cppad gave the following message.

I am using the same version but cannotget the error. Do you know why such an error would occur. I was under the assumption that no external .dll were needed for Casal2 execution, so was confused at the error message

![error](https://cloud.githubusercontent.com/assets/13144077/16511412/fc2f194a-3fa3-11e6-868d-5de969c9d86a.JPG)

**Comment by Zaita** [comment]
Do you have sample configs?

**Comment by Craig44** [comment]
[cppad_error.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/345472/cppad_error.zip)

This is definitely calling gfortran. I removed all directories in my path that contain gfortran and get the same error.

**Comment by Zaita** [comment]
This should be fixed now. Please confirm and close this issue
