### ISSUE TITLE
Conversion error in observations when miniimser == adolc

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#140]
For all the proportions observations. An error message is printed for when invoking casal2 -e when the minimiser type=adolc. Attached is the error message. It occurs converting values from a table to a double. The error doesn't occur when minimiser type = numerical_differences or betadiff
[adolc_error.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/344838/adolc_error.txt)

**Comment by Craig44** [comment]
[adolc_error.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/344873/adolc_error.zip)

**Comment by Zaita** [comment]
Fixed. Please confirm and close
