### ISSUE TITLE
estimating and rerunning @time_varying type = constant

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#141]
The issue

What I want to happen.

I want to time vary the parameter chatTANq in two blocks 1992:2005 and 2005:2012 see below

@catchability chatTANq
q 0.06970529129

@time_varying q_step1
type constant
parameter catchability[chatTANq].q
years 1992	1993	1994	1995	1996	1997	1998	1999	2000	2001	2002	2003	2004	2005	2006	2007	2008	2009	2010	2011	2012
value 0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.2	0.1	0.1	0.1	0.1	0.1	0.1	0.1

So I want to estimate two values one for the 1992:2005 and 2005:2012. I set it up to do this as follows

@estimate chatTANq_1
type uniform
same time_varying[q_step1].value(2) time_varying[q_step1].value(3) time_varying[q_step1].value(4) time_varying[q_step1].value(5) time_varying[q_step1].value(6) time_varying[q_step1].value(7) time_varying[q_step1].value(8) time_varying[q_step1].value(9) time_varying[q_step1].value(10) time_varying[q_step1].value(11) time_varying[q_step1].value(12) time_varying[q_step1].value(13) time_varying[q_step1].value(14)
parameter time_varying[q_step1].value(1)
lower_bound 0.001
upper_bound 0.40

@estimate chatTANq_2
type uniform
same time_varying[q_step1].value(16) time_varying[q_step1].value(17) time_varying[q_step1].value(18) time_varying[q_step1].value(19) time_varying[q_step1].value(20) time_varying[q_step1].value(21)
parameter time_varying[q_step1].value(15)
lower_bound 0.001
upper_bound 0.40

So essentially I estimate one of the elements and force the others to be the same. This is fine it goes away and estimates the two values then I get out parameter file as follows

process[Recruitment].r0 time_varying[q_step1].value(1) time_varying[q_step1].value(15) selectivity[chatTANSel].mu selectivity[chatTANSel].sigma_l selectivity[chatTANSel].sigma_r selectivity[eastFSel].mu selectivity[eastFSel].sigma_l selectivity[eastFSel].sigma_r selectivity[westFSel].mu selectivity[westFSel].sigma_l selectivity[westFSel].sigma_r process[Recruitment].ycs_values(2) process[Recruitment].ycs_values(3) process[Recruitment].ycs_values(4) process[Recruitment].ycs_values(5) process[Recruitment].ycs_values(6) process[Recruitment].ycs_values(7) process[Recruitment].ycs_values(8) process[Recruitment].ycs_values(9) process[Recruitment].ycs_values(10) process[Recruitment].ycs_values(11) process[Recruitment].ycs_values(12) process[Recruitment].ycs_values(13) process[Recruitment].ycs_values(14) process[Recruitment].ycs_values(15) process[Recruitment].ycs_values(16) process[Recruitment].ycs_values(17) process[Recruitment].ycs_values(18) process[Recruitment].ycs_values(19) process[Recruitment].ycs_values(20) process[Recruitment].ycs_values(21) process[Recruitment].ycs_values(22) process[Recruitment].ycs_values(23) process[Recruitment].ycs_values(24) process[Recruitment].ycs_values(25) process[Recruitment].ycs_values(26) process[Recruitment].ycs_values(27) process[Recruitment].ycs_values(28) process[Recruitment].ycs_values(29) process[Recruitment].ycs_values(30) process[Recruitment].ycs_values(31) process[Recruitment].ycs_values(32) process[Recruitment].ycs_values(33) process[Recruitment].ycs_values(34) process[Recruitment].ycs_values(35) process[Recruitment].ycs_values(36) process[Recruitment].ycs_values(37) process[Recruitment].ycs_values(38) 
3.58408e+006 0.3 0.15 7.98529 2.61927 4.02455 4.72097 4.76447 7.91373 5.06764 4.18055 7.76268 0.99513 0.982493 0.967086 0.958996 0.965375 0.977722 0.981826 0.976198 0.974177 0.396106 0.454451 0.527484 0.635475 0.767938 0.93137 1.10408 1.33398 1.34993 0.820549 0.2679 0.544116 0.347109 0.212245 0.426478 0.260142 2.48535 2.98452 0.658814 0.188896 0.372888 0.30812 0.360927 0.31001 0.263237 0.400451 0.978177 0.979505 

So I try and read it in using a -r -i and print out the time varying values.

but the report prints the values from @time_varying block and not the parameter_values_file

see the config files for reproducing.
[estimate_time_varying.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/344877/estimate_time_varying.zip)

**Comment by Zaita** [comment]
Fixed. However you'll need to update your config file. I've changed the Time_varying.constant to use the years notation instead of index as it makes no sense now that years were added. The @estimate blocks for the time_varying constant would now be:

@estimate chatTANq_1
type uniform
same time_varying[q_step1].value(2006:2012)
parameter time_varying[q_step1].value(2005)
lower_bound 0.001
upper_bound 0.40

@estimate chatTANq_2
type uniform
same time_varying[q_step1].value(1993:2005)
parameter time_varying[q_step1].value(1992)
lower_bound 0.001
upper_bound 0.40

**Comment by Zaita** [comment]
Please close once fix has been verified

**Comment by Craig44** [comment]
Cool so looking at this I have a question to ask you and @alistairdunn1. If we have set the same subcommand in an @estimate block. if I do a -r -i run do we want the -i values to overwrite all the same parameters from the @estimate block?

When I do a dash -e -i it works fine

Check two files dash_r.log and dash_e.log for the example. -r is not overwriting the report where as the -e is
[estimate_time_varying.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/356481/estimate_time_varying.zip)
