### ISSUE TITLE
Documentation syntax python script

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#148]
Change the python documentation.py to read the constructor in the order in the code base

**Comment by Craig44** [comment]
Also add the TBA keyword for exclusion in the syntax generator

**Comment by alistairdunn1** [comment]
Have now modified Documentation.py to allow for TBA keyword for exclusion in the syntax generator

**Comment by Craig44** [comment]
So I can close this issue? @alistairdunn1

**Comment by Craig44** [comment]
@Zaita The second aspect of this has been addressed the TBA fucntionality. But do you know a quick fix in the python code printing parameters from the constructor in the order that they are defined?

**Comment by Craig44** [comment]
Currently I think it prints it based on alphabetical order.

**Comment by Zaita** [comment]
Not a quick fix. Will take me a couple of hours to implement and test. Want me to do it?

**Comment by Craig44** [comment]
Yes please

**Comment by Zaita** [comment]
Fixed.
Just confirming Alistair is NOT printing any variable where the description is TBA. Shouldn't this be not printing the description of the variable but still printing the variable?

**Comment by alistairdunn1** [comment]
Yes. Where we have tba, we want to suppress both the variable and the description in the documentation.

On 23 August 2016 7:59:20 PM NZST, Scott Rasmussen <notifications@github.com> wrote:
>Fixed.
>Just confirming Alistair is NOT printing any variable where the
>description is TBA. Shouldn't this be not printing the description of
>the variable but still printing the variable?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NIWAFisheriesModelling/CASAL2/issues/148#issuecomment-241656183

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Zaita** [comment]
Done.
