### ISSUE TITLE
Nuisance q's

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#150]
Do we want to implement Nuisance q's in Casal2 @alistairdunn1 @doonanij I am replicating the 2016 SBW 6I assessment and see you are still using it Alistair.

**Comment by alistairdunn1** [comment]
Yes. There are cases where it's better. Although the best alternative is with Q's transformed by dividing/multiplying with b0. It's still useful.


On 5 August 2016 1:46:01 PM NZST, Craig Marsh <notifications@github.com> wrote:
>Do we want to implement Nuisance q's in Casal2 @alistairdunn1 @doonanij
>I am replicating the 2016 SBW 6I assessment and see you are still using
>it Alistair.
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NIWAFisheriesModelling/CASAL2/issues/150

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Craig44** [comment]
I implementing nuisance Q's, I have a query that I believe must have an elegant answer but I can not think of it. I have an estimate which contributes to the likelihood via a prior or @estimate but is not estimated but is analytically resolved before the likelihoods are evaluated. The issue, is there has to be a default value of 1 during execution but @estimate upper and lower bounds are usually in teh space 0.01-0.5 so because the @estimate has a value outside the range it errors out. @Zaita @alistairdunn1 any nice ways to resolve this?

**Comment by Craig44** [comment]
Right so I am going to set up the following.
 
@catchability chatTANq
type nuisance
prior lognormal or uniform or unifom_log
upper_bound
lower_bound
mu and cv if prior = lognormal

And this nuisance q class will create an additional prior automatically in the build and then this bypasses the estimation issues.

**Comment by alistairdunn1** [comment]
Not sure. But can you set the default as the mean of the bounds

On 16 August 2016 3:05:30 PM NZST, Craig Marsh <notifications@github.com> wrote:
>I implementing nuisance Q's, I have a query that I believe must have an
>elegant answer but I can not think of it. I have an estimate which
>contributes to the likelihood via a prior or @estimate but is not
>estimated but is analytically resolved before the likelihoods are
>evaluated. The issue, is there has to be a default value of 1 during
>execution but @estimate upper and lower bounds are usually in teh space
>0.01-0.5 so because the @estimate has a value outside the range it
>errors out. @Zaita @alistairdunn1 any nice ways to resolve this?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NIWAFisheriesModelling/CASAL2/issues/150#issuecomment-239989656

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Craig44** [comment]
Implemented and tested. I applied the functionality analogous to CASAL, it seems better adding it as an @estimate block instead of creating an additional prior.
