### ISSUE TITLE
Make CPPAD static

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#153]
Can we make CPPAD a static library. i.e not download it everytime we do a thirdparty library then the third party library wont be vulnerable to updates and bug fixes on Ipopt or CPPAD

**Comment by alistairdunn1** [comment]
Good idea ... It'll help stabilise the code. We may loose incremental improvements but it should result in fewer build errors for less experienced users

On 15 August 2016 9:29:58 AM NZST, Craig Marsh <notifications@github.com> wrote:
>Can we make CPPAD a static library. i.e not download it everytime we do
>a thirdparty library then the third party library wont be vulnerable to
>updates and bug fixes on Ipopt or CPPAD 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NIWAFisheriesModelling/CASAL2/issues/153

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Zaita** [comment]
Done

**Comment by Craig44** [comment]
Need to do for Linux build environment

**Comment by Craig44** [comment]
Can this be closed @Zaita
