### ISSUE TITLE
Estimate Transformations vs Transformations.

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#154]
I would like to discuss an alternative "EstimateTransformation", currently it takes an @estimate block and transforms it before passing to the mini miser and adding a jacobian. For example with B0 we would create an @estiamte B0 and that would specify the prior and bounds and what ever. If we want to add log transformation we would create an @estimatetransformation block linking to it. But what if we want to put the prior on LOG_B0 and estimate log_b0 explicitly

Currently with a -e the sequence goes:
RunModel() -> Evaluate Objective_fucntion()  -> transform() -> pass estimates to minimiser -> back_transform start from start.

What if with certain types of estiamte transformation it does the following:
RunModel() ->  transform() -> Evaluate Objective_fucntion()  -> pass estimates to minimiser -> back_transform start from start.

That way when priors are evaluated in the objective function they would be on there transformed space so the contribution would be from log(b0). I am open to ideas? Would this warrent a new class? 
The distinction is really the prior. should the prior be on the parameter in "model" space (Currently implemented)
or
should the prior be on the parameter in "transformed" space

They may be analytically equivalent under certain prior and transform scenerios

**Comment by Zaita** [comment]
Add a new flag to the estimate "negate_prior" that will adjust the jacobian by the prior to negate it from the likelihood. Bam... 10 minutes and implemented

**Comment by Zaita** [comment]
Update: Edited comment

**Comment by Craig44** [comment]
Come up withe some specific case examples. Think about applying specific cases for comparing lagacy functionalty, log(B0) and average difference

**Comment by Craig44** [comment]
What we need have to do for this spec is have two types of estimate transformations. 
- One that sits ontop of an @estimate block transform and add jacobian (What we have already implemented) 
@estimate_transformation
type log
estimate B0

- Second will transform an estimable parameter but will have prior, lower,upper bounds on the transformation e.g
@estimate logB0
parameter process[Recruitment].b0
transformation log
upper_bound 20 #bounds for the logged parameter
lower_bound 5
type uniform

We will have to be clever when dealing with the case average difference which is a transformation on two parameters. @alistairdunn1  can you please comment on this

**Comment by Craig44** [comment]
After talking to Alistair this is what the spec will be, three @estimate children, untransformed, transformed_with_jacobian, transformed_without_jacobian

examples of the three @estimate block types

@estimate B0
type untransformed
prior uniform
upper_bound
lower_bound
same
parameter 

@estimate log_B0
type transformed_with_jacobian
transformation log
prior uniform
upper_bound
lower_bound
same
parameter

@estimate log_B0
type transformed_without_jacobian
transformation log
prior uniform
upper_bound
lower_bound
same
parameter

**Comment by Zaita** [comment]
@estimate
type <prior>
transformation_type <untransformed, log, normal>
transform_with_jacobian <True/False>

**Comment by Zaita** [comment]
Keep @EstimateTransformation for super-complex types

**Comment by NIWAFisheriesModelling** [comment]
need to validate for transformation type in the Estimate.cpp, its currently not getting checked
