### ISSUE TITLE
single and doubled tags

### ISSUE THREAD

**Issue by smormede** [NIWAFisheriesModelling/CASAL2#158]
Need to have the capacity to have either single or doubled tag data, and how to specify the loss rate then... 
[sam-11-18.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/457865/sam-11-18.pdf)

**Comment by smormede** [comment]
I created those documents quite a while ago for this process. Some specifics still need to be discussed to make sure they fit best with the current processes.

[double tagging example.xlsx](https://github.com/NIWAFisheriesModelling/CASAL2/files/2387010/double.tagging.example.xlsx)
[multiple tagging description.docx](https://github.com/NIWAFisheriesModelling/CASAL2/files/2387011/multiple.tagging.description.docx)

**Comment by smormede** [comment]
@Zaita the documents above are probably sufficient to get this coded. I'll add whatever is missing.

**Comment by Craig44** [comment]
114f4e8f7a6e0b5f66a99bb4b3b84fb780614021
