### ISSUE TITLE
Projection::SetVectorValue() 

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#159]
I am trying to finish off projections and one of the key parameters that we put projections on are ycs_values from beverton holt recruitment process. In the Projection::SetVectorValue()  we create a pointer to the estimable vector and push_back() any projected values onto that vector line 139 of Project.cpp. which works thats fine. but when we are executing a beverton holt recruitment process and wanting to access that added element in line 293 of RecruitmentBevertonHolt.cpp the vector isn't the size it expects and so accessing non sensical values out of memory.  Can you look into this please. Cheers C

**Comment by Craig44** [comment]
Converting ycs value to a map, how to deal with an estimable map when we do not know the key (i.e year)  of the map untill DoBuild(); When the Casal2 is binding estimables it seems to do this between validate and build where this estimable isn't fully defined? @Zaita

**Comment by Craig44** [comment]
For this ycs_values key or year is related to ssb_offset_ which is defined until DoBuild() line 120

**Comment by Zaita** [comment]
After discussions, my understanding was that this could be left as a vector for projections because it's simply going to push values onto the end of the vector and they'll be used as required. Did I forget something?
