### ISSUE TITLE
Doing a -r run with an autodiff library specified

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#160]
We need a more elegant solution to this one. It is related to the dummy.cpp. I have attached some example files. You added the parameters_.set_ignore_all_parameters(); on line 27 of Dummy.cpp but the model requires a @minimiser type so it kept erroring out any time you did -r with an autodiff minimiser. I removed it from the code as you will see. But now the problem is an subcommands that are associated with an autodiff minimiser will cause an error. we need a better solution for this.
[casal_2_files.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/460661/casal_2_files.zip)

**Comment by Zaita** [comment]
Please be aware that the Dummy minimiser is required for handling various auto-differential and non-differential minimisers when they're not built into the binary. Disabling the "ignore_all_parameters()" flag will break a whole range of functionality.
