### ISSUE TITLE
Pick up the same subcommand for a -r run mode

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#162]
Currently if you give Casal2 a -i file that has been produced by an -e run. if you a -r -i or a -f 1 -i with that file, you wont get the same run as a -r doesn't find all the same sub commands in the @estimate blocks and apply the value to all the same values. This would be useful to implement.

So with -r -i run check all the @estimate blocks to see if we need to copy the value to a parameter identified in the **same** subcommmand

**Comment by Zaita** [comment]
Hmmm. Normally the -i is not bound to an @estimate unless you use the --force-estimate option. It's bound to estimables. I've put in code that will change an estimate if it exists (and it's sames)
