### ISSUE TITLE
CPPAD not minimising

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#181]
[Cppad.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/977813/Cppad.zip)
This model timed out after an hour exceeding maximum iterations. Also dumping info to the report which is useless.

**Comment by Zaita** [comment]
@Craig44 Is this still an issue?

**Comment by Craig44** [comment]
[Cppad.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/2838168/Cppad.zip)
Updated model syntax, and re-ran. I manually stopped it after ~20 mins. See Cppad.txt for results. It looks like it finds the solution space pretty quickly but doesn't terminate the search. So I believe this is still an issue. Betadiff finds a minimum in ~1 min
[cppad.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2838192/cppad.txt)

**Comment by largek** [comment]
This issue was migrated to GitLab (issue #41). It was closed there as part of V1.0 development, with no additional or supporting comments/documentation. Review before closing here.

**Comment by Zaita** [comment]
Closing. CppAD has been removed from Casal2
