### ISSUE TITLE
Create unit tests for CppAD, BetaDiff and ADOL-C.

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#184]
Create unit tests that create the specific double types and throws them through some basic tests (e.g Equation parser, standard operations, printing to stringstream etc).

This would give us more assurance that the base build is not breaking the AutoDiff builds and we can harden the autodiff integration

**Comment by Zaita** [comment]
Moving this to after v1.0. The current work on increasing test coverage and the working automated build system negates this a lot.

**Comment by Craig44** [comment]
This testing framework is in the modelrunner test suite now. There need to be more examples but, different autodiff functionality should be tested with TestModels with the frontend build
