### ISSUE TITLE
Performance/Optimisation needed

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#192]
Some where in the past months we have last speed. I have attached a simplish model with CASAL executable for comparison. 
For an estimation run -e
CASAL ~2.28mins
CASAL2 ~ 3.35 mins

this is with equivalent models starting at the same place and finishing at close points in a -e run (Note for casal2 use -i CASAL_par.txt) so they are starting at the same place

This problem grows with the complexity of the model. I will add a complex model soon, I just need to nail down why it is not replicating results in estimation.

[CASAL_EXE.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1143957/CASAL_EXE.zip)
[CASAL2.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1143959/CASAL2.zip)
[CASAL.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1143955/CASAL.zip)

**Comment by Craig44** [comment]
Nice got that same model down to 
~1.167 minutes
[estimate_optim.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/1232674/estimate_optim.txt)

Will add one more model to try and optimize. before closing this ticket

**Comment by Craig44** [comment]
An mcmc model that I CASAL is quicker.
[mcmc.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1233192/mcmc.zip)

I tested this model with CASAL ~9-11 mins to do an 100000 chain
I couldn't get a casal2 run under 18 mins for the same chain.

**Comment by Zaita** [comment]
1,000 Iterations
likelihoods::multionimial::calculatescore = 11.00%
observations::ProcessRemovealsByAge::CalculateScore 9%
process::MortalitytInstant::DoExecute 14%
observation::ProcvessRemovalsByAge::Execute() 33%
observations::ProportionsAtAge::PreExecute() 10%
accessors::cached::CombinedCategories::BuildCache() 9%
observations::ProportionsAtAge::Execute() 3%

**Comment by Craig44** [comment]
[Complex.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1241210/Complex.zip)

This is the last model that would be useful to optimise it is the most complex  age structured assessment

**Comment by Zaita** [comment]
Complex Model is done.

**Comment by Craig44** [comment]
The last model to optimise
[Test.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1397135/Test.zip)
@Zaita  will check the other issues tonight

**Comment by Zaita** [comment]
Age Length Notes:
AgeLength
- cvs_ should be map<map<vector>>> 
- Distribution should be enum

::Build()
  -> BuildCV()

::BuildCV()
- needs model->min_age(), max_age(), years(), time_steps()
- calls mean_length() a lot
- builds cvs_[year][time_step][age]
- Uses cv_first and cv_last which are addressables, so we need to trigger rebuilds
- Should be able to async this too

::CummulativeNormal(mu, cv, &prop_in_length, length_bins, distribution, plus_grp)
- This is the highest usage of CPU time
- Where is it called from??
- Goal of this method is to populate prop_in_length vector
- Has string comparisons for distribution - change to enum
- Declares a fair few local variables
- If mu and sigma do not change. Then building the tmp variable doesn't need to be repeated
- Can definitely thread off the j loop, this has no dependencies. C++11 async?
- j is only the number of length bins, so we need to check if it's worth threading, what does overhead look like?

::DoAgeToLengthMatrixConversion(category, length_bins, plus_grp, selectivity
- resizes category->age_length_matrix
- local vector creation
- Calls CummNormal once per age
- A lot of resizes... ugh 
- Again, this could be threaded with async

Schnute
::mean_length()
- You can cache the calculation of size

::DoBuildCache()
- Async
- Pre-Allocate an empty mean_length_ container

VonBert
::DoBuild()
- Async
- Pre-allocate memory

::DoRebuildCache()
- Async

**Comment by Zaita** [comment]
Partition::Category

::UpdateMeanLength()
- Should we be calling UpdateMeanWeight in a length model??
- Why would this even be called? Should LOG_CODE_ERROR()
- Async

::UpdateMeanWeight()
- Async

::CollapseAgeLengthData()
- Is data memory allocated?
- Async

::UpdateAgeLengthData(length_bins, plus_grp, selectivity)
- Do Nothing

::CollapseAgeLengthDataToLength()
- Is length_data_ pre-allocated?
- Async?
- std::accum?

**Comment by smormede** [comment]
@Zaita 
@alistairdunn1 
@Craig44 

Here's an example of really slow performance. Some model with tagging in it (Ross Sea). There's 10 years of tagging and sexed model.
casal: 8 minutes
casal2: 54 minutes

Happy to test any changes. Might be linked to issue #210 where casal2 fails with more partitions.

[CASAL2nuisance10yrTagsNormalAeging.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1666402/CASAL2nuisance10yrTagsNormalAeging.zip)
[CASAL10yearTags.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1666403/CASAL10yearTags.zip)

**Comment by smormede** [comment]
Updated toothfish model from above with 13 years of tagging (now works with larger partitions) and also the new global length bins:
casal 18 minutes
casal2 29 minutes

[rsr model performance.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/2459016/rsr.model.performance.zip)

**Comment by Craig44** [comment]
One thing I have noticed between Casal2 runs and CASAL runs is how much the call for betadiff to resize is. With Casal2 betadiff seems to have to make a lot more room for memory. When I re-run these two models see the betadiff resizing for each model @Zaita  I think this might be give a hint to the route of the problem
[casal2_resizing.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2459300/casal2_resizing.txt)
[casal_resizing.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2459301/casal_resizing.txt)

**Comment by Zaita** [comment]
@Craig44 That is a symptom of poorly optimised code. The resizing will be occuring because the chain is getting longer because code in Casal2 is not allocating memory appropriately. This is the known cause of a large part of the Casal2 slowdown that has occurred.

**Comment by Zaita** [comment]
Note: In rsr_model_performance: 66% of all execution time is spent in Mortality Instantaneous

**Comment by smormede** [comment]
@Zaita can that slowdown and memory issue be fixed? I assume this is the issue for it or does it need to be another issue raised? Seems pretty critical to me to get this sorted?

**Comment by Craig44** [comment]
I have a model that displays interesting (less than ideal) behaviour, that might shed light on this. It's based on the SNA1 assessment. When I change the max_age from 20 to 45 the betadiff memory resizing doubles!!! The question I have is should this happen? Also for the equivalent CASAL model, betadiff doesn't have to write to tape but for the Casal2 mode does.... which is undesirable. I have attached the models in a zip file. 
[Issue192.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/3444490/Issue192.zip)

**Comment by largek** [comment]
This issue migrated to GitLab (issue #39) but not addressed as part of V1.0 development. Critical issue that needs work.

**Comment by Craig44** [comment]
Recent code changes and comparisons have shown Casal2 to be faster than CASAL for most complex models. Always need to do more optimisation, but closing for now
