### ISSUE TITLE
LengthBased Functionality

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#194]
See this syntax: @alistairdunn1  @doonanij  @largek 
for a simple length based model in Casal2, no comment will be taken as approval.

[config.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/1178962/config.txt)

**Comment by Craig44** [comment]
Remove the concept of age and length internally in the model and replace it with 'class' that way most of the functionality can be kept in the Common section. so we can call model->classes() which will read a vector<unsigned> classes_ instead of age and length.
in an age based model classes_ = min_age : max_age
and in a length based model
classes_ = length_bins_

**Comment by Craig44** [comment]
I think this is what we will do @Zaita  unless there objections.

**Comment by Craig44** [comment]
in the @model we still have either length_bins or min_age max_age, but internally these are called off the model or categories as partition bins.

model_->partition_bins() // returns 1 2  3 4 5 6 7 8 9 for a hypothetical age case
2 4 6 8 10 12 23 for a hypothetical length scenario

remove the concept of age and length from the model that way we can keep 70% of the code in common. One of the major changes will be that we can't have min_bin() because for length based models there is no guarantee that the bins are incremental. So we will have to get rid of code that create age offsets such as model_->min_age() + i;

**Comment by Craig44** [comment]
For this tick to be closed. We need a simple operating model that, has growth, recruitment, constant mortality and a derived quantity.

**Comment by Zaita** [comment]
Note: We will not be moving age and length into a common container (e.g. classes) as this would destroy the performance of Casal2.

**Comment by Craig44** [comment]
See merge 40ca5c7557d59ad2e2e9ed99c79acc521b148819 for LengthBased inclusion into Casal2
