### ISSUE TITLE
Add @assert blocks to model runner models

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#199]
Right now, there is no validation on the consistency of these. Please add @assert blocks to the new ones you've added. See the basic ones I added as examples in population.csl2

**Comment by Craig44** [comment]
For the TestModels I have added, there are @assert blocks in the report.csl2? If that's not what you mean can you explain further please.

**Comment by Craig44** [comment]
@Zaita Can you elaborate on this? otherwise I will close this issue
