### ISSUE TITLE
Add a IsInfinite() function in Utilties/DoubleCompare.h

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#200]
I have come across some weird behaviour where, the betadiff minimsier can actually build up a hessian value = Inf or -Inf, I want to be able to catch this at BuildCovariance() in Minimiser.cpp so that we can log a fatal. I have found that is tied to parameters at bounds, the implication of this is it propogates nan through the covariance matrix which can mess up MCMC's etc. test model attached. When I remove the parameters of interest process_error parameters everything works, as is expected.

**Comment by Craig44** [comment]
[Inf_example.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1290257/Inf_example.zip)

**Comment by Zaita** [comment]
C++ has a native isinf method to check if a number is infinite.
http://en.cppreference.com/w/cpp/numeric/math/isinf
