### ISSUE TITLE
Add functionality to incoperate dietary observation in hollings mortality process

### ISSUE THREAD

**Issue by jzha336** [NIWAFisheriesModelling/CASAL2#207]
Current hollings mortality rate process contains a predator and a prey selectivity function. The objective of adding this functionality is to enable using dietary observations to replace the prey and predator selectivity functions.
After adding this function, the current predator selectivity will become replaceable by the prey proportion in predator's stomach contents (age-year observations). The current prey selectivity will become replaceable by the likelihood of prey being eaten by the predator over year (age-year observations). 
[dietary observation for hollings.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/1553970/dietary.observation.for.hollings.txt)

**Comment by jzha336** [comment]
The predator selectivity has limited impact on the prey age-year structure, and the Hollings type II function does not allow a feedback loop for predator number/partitioning by the change of prey number. Because of these reasons, this issue will focus on developing functionality to incorporate and estimate prey selectivity observations in the Hollings mortality process only.

**Comment by Craig44** [comment]
[hollings_model.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1580482/hollings_model.zip)

Added, look at test model attached: line 442 in population.csl2.
You can either specify a table of selectivity by year and age, for both prey and predators,

Also you can report on the holling process as well. @jzha336  can you test and close this issue. A exe should be ready in 2 hours

**Comment by jzha336** [comment]
This function has been added to the CASAL2 new version.
