### ISSUE TITLE
Global length bins in an age based model

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#208]
A spec  which I believe has started but would be great to finish is to create a length_bin subcommand on the @age_length block. Have a switch (where appropriate, @model or on the @age_length, use_global_length_bins) so we can build lookup by age_length, year and time_step return the age_length matrix. Instead of calculating this every time in the fly

This spec is for Age based models, that use length based processes/observations

Most of this code should be written in the age_length class.

Business rules:
For any process/observation we must check that if use_global_length_bins = True then check the user has supplied the same length bins in the process/observation that are on the age_length class. Error out with sensible warning if not.

**Comment by Zaita** [comment]
length_bins are specified on the @model object (this is where ages are also specified). 

Processes/Observations that need to override these will be able to do so. But for now everything defaults to using the global length_bins. This was implemented because it's significantly faster

**Comment by Zaita** [comment]
Moving to after 1.0 as this has been implemented. Improvements to individual objects will be made as needed.

**Comment by largek** [comment]
This issue replaced by GitHub issue #343, which was a migrated from GitLab (issue #43).
This issue was investigated, resolved and closed as part of V1.0
