### ISSUE TITLE
casal2 -e beta diff error

### ISSUE THREAD

**Issue by smormede** [NIWAFisheriesModelling/CASAL2#209]
Model run:
casal2 -e > estimate.log
error:
FATAL BETADIFF ERROR - consult a maintainer.
Succeeding reverse sweep will fail! operation=107, arg=620865, T0[arg]=1

Only difference compared to another run that worked is that I have growth for tagged fish 0.5 offset to that of not tagged fish. Might or might not be the issue.

thanks

Sophie
[CASAL2bdiffError.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1573722/CASAL2bdiffError.zip)

**Comment by Craig44** [comment]
@smormede  when did this error occur at the beginning of estimation or partway through?

**Comment by smormede** [comment]
OK I'm completely stumped because i reran it to check where exactly it failed (sometime during the run) and it ran. I even rerun the exact files I attached here and it ran. Yet there's proof it was the same place with estimate.log.
Best we close this and reopen if we can replicate.
