### ISSUE TITLE
Create a stable version of Casal2 and freeze/archive it

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#212]
At some point, Maybe create a list of things we need to accomplish before we are happy to version Casal2
- Finish length based model functionality
- Tidy documentation up with age and length syntax files
- Version Casal2

**Comment by smormede** [comment]
Hi there,

To add to the list:

•	Make it run faster so it can be useable with length-based observations in age-based model. Ross Sea stock assessment MPD currently 8 minutes on casal and 54 minutes on casal2.
•	Fix that bug where it’s failing with more partitions.

In this state it's not usable at CCAMLR.

Thanks

Sophie

**Comment by Craig44** [comment]
I think this should be a priority and I am thinking that we make the master repo purely age base keep the Source/age and Source/Common directories and have a branch for the length based functionality. Only bring in the length based functionality when there is a minimum working assessment, complete documentation and unit tests.
