### ISSUE TITLE
TaggingByLength calculating invalid total_stock_with_selectivities

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#215]
[orig.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/1786708/orig.zip)

When TaggingByLength is calculating total_stock_with_selecitivities it's going past the end of the array and reading invalid memory. This is causing different results with each run.

https://github.com/NIWAFisheriesModelling/CASAL2/blob/master/CASAL2/source/Age/Processes/Children/TagByLength.cpp

Line 312 will iterate over the length_bins which is the defined bins + max_length because length_plus is false. When it gets to the last element which is now length 230 this is past the end of the length_data_ vector on the category.

i: 20; (*from_iter)->length_data_[i]: 0.999772; (*from_iter)->length_data_.size(): 20
[FINEST] ..\source\Age\Processes\Children\TagByLength.cpp(line: 327): total_stock_with_selectivities: 0.999772 at length 230

0.999772 is random because it's undefined memory.

**Comment by Craig44** [comment]
Did this get resolved?

**Comment by SamikDatta** [comment]
Hey Craig,

Thanks for reminding me, I’ll try to get onto this later this week.

Samik.

**Comment by Zaita** [comment]
I believe so.
