### ISSUE TITLE
Change build command line parsing to allow for threads option

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#218]
Number of threads used for building is low because of low-spec automated build system. Suggest --threads command line option so high performance systems (like mine) can use multiple threads.

FWIW, I edit my build to use 12-15 threads. Build system runs like 1-2

**Comment by Craig44** [comment]
I do this as well, it is a pain to have to change the builder.py every time, can you add it to python script @Zaita

**Comment by Zaita** [comment]
also adding the ability for the build system to do an incremental build instead of rebuilding everytime. This will cut a build from 3+ minutes to ~10 seconds.

**Comment by Craig44** [comment]
So does that mean we can close this issue?

**Comment by Zaita** [comment]
It means if you're going to modify the build system to support threads, you might as well support incremental builds as an option too (or default, with full as option)

**Comment by Zaita** [comment]
Closing. Build system now supports CASAL2_BUILD_THREADS environmental parameter to specify the number of threads it will use during the build.
