### ISSUE TITLE
Development of multi-threaded MCMC or MPD.

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#228]

**Comment by Craig44** [comment]
Is this not the same as #15

**Comment by Zaita** [comment]
Similar but different. This is specifically MCMC or MPD.

#15 is about general inclusion of threading across models. #15 would be a pre-req for this,

**Comment by Craig44** [comment]
Much of this functionality was added with this commit. Documentation needs to be added for Hamiltonian MCMC 2dc59d09d64eda3c34c84f75960e3690f55a6c4f
