### ISSUE TITLE
ADD Laplace approximation for integrating over random effects at MPD estimation

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#229]
So I have been looking at the Laplace approximation and it seems relatively straight forward in theory, but the implementation might be difficult hopefully, all developers have access to the development repo as I have added a whole lot of information on how it is implemented in other software ADMB, TMB see [here](https://github.com/NIWAFisheriesModelling/CASAL2_Development/tree/master/Future%20specs/Laplace%20approximation)

Approx time of implementation 12 hrs 

Will need 10+hours for unit testing as it is a fundamental change, but I am happy to tick away with this I have age structured models in TMB that can be used to validate this functionality

**Comment by hoyles** [comment]
That link doesn't seem to work.

**Comment by Craig44** [comment]
Someone will need to subscribe you to that repo it is aprivaterepo
