### ISSUE TITLE
Fatal error when doing an MCMC if the user attempts to define a MCMC_objectives or MCMC_samples report

### ISSUE THREAD

**Issue by alistairdunn1** [NIWAFisheriesModelling/CASAL2#230]
CASAL2 generates a fatal error when doing an MCMC if the user attempts to define a MCMC_objectives or MCMC_samples report

CASL2 creates a default MCMC samples and objectives reports if one is not defined by the user. If the user attempts to create an MCMC samples or objectives report, CASAL2 exits with the fatal error:

********************************************************************************
********                CODE ERROR - CASAL2 is FORCE QUITTING           ********
********************************************************************************
Source File: C:\Projects\Software\CASAL2\CASAL2\source\Common\Reports\Children\MCMCObjective.cpp(line: 39)
Source Method: DoBuild

Message:
mcmc_ = model_->managers().mcmc()->active_mcmc();
NOTE: This error is a bug in the software and can be corrected by a developer
Please contact the application developers at casal2@niwa.co.nz to have this issue fixed

**Comment by Zaita** [comment]
Fixed. Now MCMC only creates reports if they haven't already been specified.
