### ISSUE TITLE
Rename the CASAL2 UserManual

### ISSUE THREAD

**Issue by alistairdunn1** [NIWAFisheriesModelling/CASAL2#232]
The Casal2 user manual has the file name UserManual.pdf. This should be renamed "Casal2 User Manual.pdf" to assist finding the document when installed on users systems

**Comment by SamikDatta** [comment]
I can build the archive fine on my machine (Windows), so there must be a Linux / machine-specific problem with your build, Marco. There are two places where the user manual lives:

(1) Documentation\UserManual\CASAL2.pdf
(2) BuildSystem\Casal2\UserManual.pdf

The first is rebuilt if you do the command 'dobuild documentation' in Buildsystem.
The second is rebuilt if you do the command 'dobuild archive' in Buildsystem. (I'm guessing it simply copies the file over to the first location with a name change, which should be the key here).

I assume it is the second file which wants to be renamed, from Alistair's initial post. I have played around at renaming the first file, with limited success - so far, I can get it to be renamed (by playing around with lines 663-687 of BuildSystem\buildtools\classes\Documentation.py), although I haven't gotten the references to display yet. I will investigate further.

**Comment by mkienzle** [comment]
super Samik!

can I leave this to you?

**Comment by Zaita** [comment]
Dobuild.sh documentation to generate user manual
