### ISSUE TITLE
tagging in models

### ISSUE THREAD

**Issue by smormede** [NIWAFisheriesModelling/CASAL2#235]
The whole tagging processes need to be tested again (tagging with associated selectivity, initial mortality, ongoing tag loss). Some code has been reverted since they were tested last. Also unit tests need to be built.

**Comment by smormede** [comment]
MCMC runs also need to be tested. Those failed, and I'm not sure if it was an issue specific to the tagging model or not. 
This is also a good model structure to test speed on as has many partitions (see issue #210 ) , when last tested was too slow to be useful.

**Comment by Zaita** [comment]
MCMCs will not work with the standalone binaries. You need to use the full Casal2 package that includes both auto-differentiation minimisers and not.

This is the package that should be available on the NIWA FTP.

**Comment by smormede** [comment]
Thanks for the clarification and package. Here's the new error, still same model as in #192 . Could be related to size issue and that issue I just closed.

ADOL-C error: unable to remove old tapefile
ADOL-C error: Fatal error-doing a write 0--- error 22
Unexpected unix file error-- 22.

I have files 
_adol-op_tape
_adol-rl_tape
_adol-in_tape

**Comment by Craig44** [comment]
Validated and added compatibility in commit 71f5ea5f2cc945726173e819eedf40876f4edcf7
