### ISSUE TITLE
Unit Test code missing unit tests

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#236]
Lots of new code added by NIWA does not have unit tests. This code needs unit tests to verify integrity before version 1.0

**Comment by mkienzle** [comment]
@Zaita @smormede @alistairdunn1 @Craig44 @alistairdunn1 @NIWAFisheriesModelling @SamikDatta 

Please, provide a detailed list of code you have in mind that needs unit tests to make this issue more specific

**Comment by Zaita** [comment]
All .cpp files that do not have a .Test.cpp file with working unit tests covering >80% of code paths.

**Comment by mkienzle** [comment]
I attached a list of 245 cpp files that have no Test.cpp files. Surely there will be file that don't need a unit test. If I miss any, please add to the list.

Could (all of) you go through this list to identify those that you would like to have a unit test done to it?

[ListOfCppFilesWithoutTest.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2412762/ListOfCppFilesWithoutTest.txt)

**Comment by SamikDatta** [comment]
Hi @Zaita - @mkienzle and I have started looking at the Google testing framework and developing simple tests to make sure we know what we're doing. Marco has gotten a lot further than me!

Is there a way to test that a unit test is functioning, without incorporating it into Casal2? (For example, a function that calculates the square root of a number, and then giving it some examples with expected output - this is what Marco has done.) I see that googletest is installed as a third-party library in the following location:

ThirdParty\googletest_googlemock

Is there a straightforward way to utilise this library to run a unit test? Marco has managed to get things going on Linux outside of Casal2, but I have not been able to replicate this on Windows.

**Comment by Zaita** [comment]
The method for doing this on Windows and Linux should be pretty much the same. The header files and libs will live in Casal2\BuildSystem\bin\windows\thirdparty\

**Comment by mkienzle** [comment]
There is a problem with ListOfCppFilesWithoutTest.txt because CASAL2/source/AgeLengths/Age/VonBertalanffy.cpp
 does have a Test.cpp associated.

A new list of age processes lacking unit test was attached [ListOfAgeProcessesMissingUnitTest.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2481052/ListOfAgeProcessesMissingUnitTest.txt).

**Comment by smormede** [comment]
can we make natural mortality top priority to help @Zaita optimise this unit and speed up the model. thanks.

**Comment by mkienzle** [comment]
following @Zaita 's suggestions and [Erik Smistad tutorial](https://www.eriksmistad.no/getting-started-with-google-test-on-ubuntu/), a simple C++ code that demonstrates how to use [google testing framework](https://github.com/google/googletest) to build unit tests for CASAL2 is provided below. 

#ifdef TESTMODE

#include <gtest/gtest.h>

TEST(MyFirstTest, TestDescription){

  EXPECT_EQ(true, true);  // expect equal
  EXPECT_NE(true, false); // expect not equal
 }

#endif /* TESTMODE */

To try the code for yourself, copy and save it in a file (for example MyFirst.Test.cpp located in CASAL2/source/Processes/Age)

Then compile an executable using (on linux) the following command: ./doBuild.sh test
Execute the test using the following command: casal2 --gtest_filter=*MyFirstTest*

**Comment by SamikDatta** [comment]
This works on Windows, too - after creating the above file (you can name it whatever you want), compile the test executable using dobuild test on Buildsystem, and then go into the bin/windows/test folder and run the command casal2 --gtest_filter=MyFirstTest.

One thing, @Zaita - when I rebuild the test executable it goes through each and every file, not just ones that have been added or updated, taking 7-8 minutes. When Marco rebuilds on Linux, it only looks at modified files, and takes ~20 seconds. Is there a way to rebuild smartly on Windows?

**Comment by SamikDatta** [comment]
Just for future reference, when adding a unit test from scratch, after adding the .cpp file in your directory, you need to be in Buildsystem, and run the command `dobuild test`. Once this has successfully completed, you can go into the subfolder bin/windows/test, and after editing the unit test simply run `mingw32-make` to _update_ any tests which have changed (hence taking a few seconds rather than building from scratch).

**Comment by Craig44** [comment]
unit tests will continue to be added, and will close for now.
