### ISSUE TITLE
cannot build documentation on mac os x

### ISSUE THREAD

**Issue by pletzer** [NIWAFisheriesModelling/CASAL2#239]
When I do 

./doBuild.sh documentation I get 

....
parameter Time\_Varying
-- Building latex documentation and pdf
-- Building CASAL.syn
-- Build version.tex with Git log information
sh: bibtex.exe: command not found

###### ERROR ######
Error Description:
bibtex failed
###### ERROR ######

--> Finished 
Error Occurred
niwa-1019500:BuildSystem pletzera$ which bibtex
/Library/TeX/texbin/bibtex

Looks like it is trying to use bibtex.exe on Mac OS X (?)

**Comment by Zaita** [comment]
Closing. Casal2 does not support MacOS
