### ISSUE TITLE
Small bug in initialization type derived

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#249]
I Found a small bug that is easily fixed which has occurred a [this line](https://github.com/NIWAFisheriesModelling/CASAL2/blob/aeddbdde9425312f9d7f426fa94dd8ae3822bf25/CASAL2/source/InitialisationPhases/Age/Derived.cpp#L275) That line wants to move up to line [273](https://github.com/NIWAFisheriesModelling/CASAL2/blob/aeddbdde9425312f9d7f426fa94dd8ae3822bf25/CASAL2/source/InitialisationPhases/Age/Derived.cpp#L273), only an issue when casal_initialisation_switch true.

**Comment by mkienzle** [comment]
Samik's pull request effectively fixed this bug.
