### ISSUE TITLE
An error with age length pointers that should be caught because I cannot see why it is triggered

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#257]
[Tag_error.txt](https://github.com/NIWAFisheriesModelling/CASAL2/files/2432655/Tag_error.txt) Seems to have come in on the new age-length spec @Zaita can you see why this error comes about?

**Comment by Zaita** [comment]
Cause: @model not having length_bins specified. Added check to TagByLength process to detect this.

**Comment by SamikDatta** [comment]
Hi @Zaita , thanks very much for this fix - hopefully this helps Sophie with her current issue, and also in the near future when older Casal2 files crash with the most recent build, due to the change in syntax.

**Comment by Craig44** [comment]
Can you close this issue?
