### ISSUE TITLE
Remove real data from repo

### ISSUE THREAD

**Issue by SamikDatta** [NIWAFisheriesModelling/CASAL2#272]
Look through test cases, make sure that none of the files contain real data (these should not be available publicly). Remove and store somewhere safe on NIWA drive.

**Comment by SamikDatta** [comment]
This is more difficult than I first thought, to delete files not just from the repo but from the entire Git history. I have found a couple of resources with commands to follow:

https://stackoverflow.com/questions/10067848/remove-folder-and-its-contents-from-git-githubs-history

https://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-git-repo

My first attempt was not successful - it takes a long time (15-20 minutes) to delete a folder, and then the dereferencing part is what didn't work for me. I will keep plugging away at this.

**Comment by hoyles** [comment]
I've used the BFG open source tool successfully in the past.  See https://help.github.com/articles/removing-sensitive-data-from-a-repository/.

**Comment by Zaita** [comment]
Please provide a list of files or models you want removed. I can remove these from history as well, we do this when we update Boost because of the size, so it's not first time we've done this.

**Comment by SamikDatta** [comment]
Hi @Zaita - the two folders (which are deleted in the repo but not the history) are:
CASAL2\testcases\CASAL2vsCASAL\HAK4
CASAL2\testcases\CASAL2vsCASAL\SBW

**Comment by Zaita** [comment]
Done.
