### ISSUE TITLE
keeping shipping or not CASAL2 with old libraries

### ISSUE THREAD

**Issue by mkienzle** [NIWAFisheriesModelling/CASAL2#276]
There is no doubt that software is constantly evolving and mathematical libraries are no different. CASAL2 uses old libraries (Betadiff, Adol-C) which are not maintained anymore. This poses at least 2 problems (1) as the computer hardware improves it becomes more likely impossible to compile and use those libraries and (2) newer, faster mathematical methods are not implemented in these old libraries. The management of CASAL2 project might have at some point to decide to stop or not to provide access to one or more of these older libraries.

**Comment by Zaita** [comment]
Betadiff is custom NIWA code. Adolc that betadiff uses is old. Betadiff
itself still gets annual updates. It's pretty stable so updates are less
frequent, but still seems actively supported

**Comment by Zaita** [comment]
@smormede How do you want to handle this?

I would note that the code in Betadiff is ~20 years old and while we've had to do some minor tweaks to it, we've had no issues compiling with the latest set of compilers or Operating Systems. 

I'm happy to close this as a non-issue, as this is standard for any development project. The biggest challenge Casal2 faces is the use of auto-differentiation libraries. These severely limit the third-party libraries we can use as every library must support custom types. For Casal2 this covers CppAD, ADOL-C and BetaDiff.

**Comment by smormede** [comment]
@Zaita I would leave it for now and close it. If / when we have a solution to that then we can implement. Thanks

**Comment by largek** [comment]
This issue was migrated to GitHub (issue #38) and never addressed nor closed.

**Comment by Zaita** [comment]
Closing. Libraries has been trimmed from Casal2.
