### ISSUE TITLE
Add MINUIT2 as a minimiser to casal2 to compute Hessian, matrices of var/cov

### ISSUE THREAD

**Issue by mkienzle** [NIWAFisheriesModelling/CASAL2#277]
[MINUIT2](https://root.cern.ch/root/html534/guides/users-guide/MathLibraries.html#minuit2-package) is the popular minimisation library developed at CERN ([www.cern.ch](www.cern.ch) and used in High Energy Physics to estimate model parameters. This library, as well as many other [mathematical libraries](https://root.cern.ch/root/html534/guides/users-guide/MathLibraries.html) written in C++, are open source, freely available and can be downloaded at [www.cern.ch](www.cern.ch) following the links included in the present text. This library will return the hessian matrix. Its usage is fully documented on CERN’s webpages and examples are provides with [ROOT](https://root.cern.ch/) (their modular scientific software toolkit) source code, for example: [https://root.cern.ch/root/html/tutorials/fit/Ifit.C.html](https://root.cern.ch/root/html/tutorials/fit/Ifit.C.html). According to Scott Rasmussen, basic integration of this library into CASAL2 looks straight forward.

If you are interested in how MINUIT has been used in the context of fisheries stock assessment software, you can have a look at [this paper](https://www.sciencedirect.com/science/article/abs/pii/S0165783614000769) and [this paper](https://www.sciencedirect.com/science/article/pii/S0304380015005293?via%3Dihub) and [this GitHub repo](https://github.com/mkienzle/DelayDifference). This series of papers describe an implementation of the delay difference that uses MINUIT2. A range of models ( > 100)  with various processes and parameters fitted with this software to determine which hypotheses, about the working of this fishery, were most supported by the data. This mathematical library was used to estimate up to 49 parameters. The implementation was tested until the software was shown to be capable of estimating all the parameters of interest for the fishing industry to understand its dynamics.

**Comment by Craig44** [comment]
We will move this to a list of future features list, rather than keeping as an open issue.
