### ISSUE TITLE
Fix report partition_mean_weight

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#281]
Currently the report is  model_state_ = State::kExecute;
when you estimate with this report on it prints every execution which is not ideal, first because those reports are generated from parameters that are candidate not likely values, and second it will be inconsistent with other reports, I think it would be best to be changed to State::kIterationComplete

**Comment by largek** [comment]
The reports partition_mean_length and partition_mean_weight have been worked on, but need to be checked with time-varying parameters.
