### ISSUE TITLE
tag module wrong

### ISSUE THREAD

**Issue by smormede** [NIWAFisheriesModelling/CASAL2#283]
While testing casal2 for multiple tagging we realised that the tagging module is now wrong. The number of tagged fish is wrong (but up to hundreds of thousands) and the ratio of males to females is also wrong. This is on Version: 2019-01-15 20:31:26 UTC (rev. 3a740055)

This module was successfully tested on Version: 2017-12-15 00:48:24 UTC (rev. fca9d8d) back in 2017. Number of tagged fish, proportions of males and females and tag loss was all accurate.

It looks like an update between those two versions has compromised the tagging numbers. This also highlights the need for unit tests for these modules.

**Comment by smormede** [comment]
Further testing shows that if the length bins in the tagging module are identical to the generic bins, then the module looks like it tags the right number of fish sometimes but the proportion of males to females is wrong, and if the selectivity doesn't go to 1, then the number of fish tagged might also be wrong.

This points out to an issue introduced when generic length bins were added and it might also impact on other length-based processes and observations.

**Comment by Craig44** [comment]
Validated and added compatibility in commit 71f5ea5f2cc945726173e819eedf40876f4edcf7
