### ISSUE TITLE
Document all valid options for commands, subcommands, and parameters (GitLab issue #4)

### ISSUE THREAD

**Issue by largek** [NIWAFisheriesModelling/CASAL2#309]
I haven't found in the documentation where the correct spelling and usage of estimable parameters is specified. For instance, the double normal selectivity has 4 parameters, specified in the input files as 'mu', 'sigma_l', 'sigma_r', and 'alpha'.  The documentation has unclear specification of the equation and the parameters.

Screenprint: [Document all valid options for commands, subcommands, and parameters (#4).pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/5544294/Document.all.valid.options.for.commands.subcommands.and.parameters.4.pdf)

**Comment by Craig44** [comment]
this should be outlined in the syntax section of the user manual. If there are specific examples please add, otherwise closing for now
