### ISSUE TITLE
doBuild RLibrary is trying to modify global filesystem (GitLab issue #21)

### ISSUE THREAD

**Issue by largek** [NIWAFisheriesModelling/CASAL2#326]
When I run doBuild rlibrary (Linux) it's attempting to install the Casal2 libraries directly on to the local file system. doBuild.sh should not be modifying the local system outside of the BuildSystem folder hierarchy.

If the BuildSystem is going to install stuff locally, this should be done through a separate argument and should ask the user for confirmation before modifying the local filesystem.

This also assumes the user has permission to modify the R folder, in many scenarios this would not be the case and on Linux you'd need to invoke the command with sudo. (e.g. on my system, I use the user nobody and this user does not have permission to write to ‘/usr/lib64/R/library’)

See attached run.log lines 59+

Screenprint: [doBuild RLibrary is trying to modify global filesystem (#21) · Issues · Fisheries _ modelling _ Casal2 Development · GitLab.pdf](https://github.com/NIWAFisheriesModelling/CASAL2/files/5773094/doBuild.RLibrary.is.trying.to.modify.global.filesystem.21.Issues.Fisheries._.modelling._.Casal2.Development.GitLab.pdf)

**Comment by Zaita** [comment]
Fixed in master/HEAD
