### ISSUE TITLE
CppAD executable output does not produce a covariance matrix (GitLab issue #36)

### ISSUE THREAD

**Issue by largek** [NIWAFisheriesModelling/CASAL2#341]
The covariance matrix produced by the CppAD version of the executable on both Windows and Linux is the identity matrix.

The calculated covariance matrix should be output.

Screenprint: [Uploading CppAD executable output does not produce a covariance matrix (#36) · Issues · Fisheries _ modelling _ Casal2 Development · GitLab.pdf…]()

**Comment by Zaita** [comment]
Closing. CppAD has been removed from Casal2.
