### ISSUE TITLE
[BUG] Casal2 is VERY slow

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#351]
**Describe the bug**
The performance in Casal2 has changed significantly and is much worse. Performance has gone from being ~30% faster than Casal to now 10-100x slower.

**Release version(s) and/or repository branch(es) affected?**
Version 1.0
All branches
master

**Operating system type and version (and build tools types and versions, if applicable)**
All

**Steps to reproduce the bug**
N/A

**Expected behavior**
Casal2 would be comparable to Casal in speed on similar models.

**Actual behavior**
Casal2 is 10-100x slower. Especially with MCMC runs where Casal can take hours and Casal2 can take weeks/months.

**Screenshots**
N/A

**Additional context**
N/A

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read the Contributors Manual and the Contributors Guidelines before starting any work).

**Comment by Craig44** [comment]
This will be forever a 'bug' with continuous optimisation to be done. should be closed, not helpful staying open.
