### ISSUE TITLE
Casal2 v1.1.0 does not compile on Windows (CppAD failure)

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#357]
**Describe the bug**
CppAD third-party does not compile on Windows, so unable to complete third-party compilation to build binaries.

**Release version(s) and/or repository branch(es) affected?**
Casal2 V1.1.0 release - downloaded source code 

**Operating system type and version (and build tools types and versions, if applicable)**
WIndows 10 - TDM-GCC 10.3.0

**Steps to reproduce the bug**
Download https://github.com/NIWAFisheriesModelling/CASAL2/releases source code zip from this location and attempt to build it.

**Expected behavior**
Casal2 third party would build

**Actual behavior**
Casal2 third party build fails

**Screenshots**
![image](https://user-images.githubusercontent.com/1491276/126583671-681e8a71-27d2-4667-9a39-e3d7846aa0c1.png)

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read the Contributors Manual and the Contributors Guidelines before starting any work).

**Comment by Craig44** [comment]
No longer supporting CPPAD so closing.
