### ISSUE TITLE
Process reports that attempt to report with an invalid process label give a critical error

### ISSUE THREAD

**Issue by alistairdunn1** [NIWAFisheriesModelling/CASAL2#360]
**Describe the bug**
Process reports that attempt to report with an invalid process label give a critical error

**Steps to reproduce the bug**
@report MyLabel
type process
process NotAValidProcessLabel

**Expected behavior**
A  standard error message

**Actual behavior**
CODE ERROR: A critical error has occurred:
(!process): NotAValidProcessLabel
This is a critical error in the Casal2 code base.
Please contact the Casal2 Development Team at casal2@niwa.co.nz to report this  error

**Release version(s) and/or repository branch(es) affected?**
Current branch

**Operating system type and version (and build tools types and versions, if applicable)**
Windows 

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read the Contributors Manual and the Contributors Guidelines before starting any work).

**Comment by Zaita** [comment]
Fixed in Master/HEAD
