### ISSUE TITLE
Specifying more than one autodiff minimiser (with only one active) causes an error

### ISSUE THREAD

**Issue by alistairdunn1** [NIWAFisheriesModelling/CASAL2#362]
**Describe the bug**
Specifying more than one autodiff minimiser (with only one active) causes a syntax error

**Release version(s) and/or repository branch(es) affected?**
Version 1.0

**Operating system type and version (and build tools types and versions, if applicable)**
Windows

**Steps to reproduce the bug**
@minimiser betadiff
type betadiff
covariance True
active false

@minimiser adolc
type adolc
covariance True
active true

**Expected behavior**
No error, and Casal2 runs with the active minimiser

**Actual behavior**
Casal2 reports the following:

Casal2 has found syntax errors in the input configuration file:

At line 2 in config/estimation.csl2: Block object type or sub-type is invalid.
Object Type: minimiser
Sub-Type: betadiff

**Screenshots**

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read the Contributors Manual and the Contributors Guidelines before starting any work).

**Comment by Zaita** [comment]
Fixed in Master/HEAD

**Comment by Zaita** [comment]
Note: Also fixed a bug where you'd get an error if you specified multiple different auto-diff minimisers and one of them was active. Casal2 would not recognise the non-active one as a valid block of configuration.
