### ISSUE TITLE
Error when using casal2 -fi 

### ISSUE THREAD

**Issue by alistairdunn1** [NIWAFisheriesModelling/CASAL2#363]
**Describe the bug**

Using casal2 with the "--fi" option to force the input file to have only estimated parameters results in incorrect output

**Release version(s) and/or repository branch(es) affected?**
Release version 1.0

**Operating system type and version (and build tools types and versions, if applicable)**
Windows

**Steps to reproduce the bug**
In \TestModels\TwoSex_input 

running

..\..\BuildSystem\bin\windows_gcc\release_betadiff\casal2 -r --fi pars.out > a.log

results in the assert error

"[ERROR] ../CASAL2/source/Asserts/Common/ObjectiveFunction.cpp(line: 55): Assert Failure: Objective Function had actual value 2033.47 when 1782.72 values were expected with difference: 250.747"

**Expected behavior**
Identical output to "casal2 -r -i pars.out" should be produced

**Actual behavior**
Assert failure, and the free parameters used are not those in pars.out

**Screenshots**

**Additional context**
casal2 -r -i pars.out works as expected

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read the Contributors Manual and the Contributors Guidelines before starting any work).

**Comment by Zaita** [comment]
Fixed in Master/HEAD

Correct command line call is : Casal2.exe -e -i pars.in --force
Not
Casal2.exe -e --force pars.in 
etc
