### ISSUE TITLE
Dirichlet multinomial likelihood

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#401]
There is a branch that has implemented 90% the dirichlet multinomial likelihood.https://github.com/NIWAFisheriesModelling/CASAL2/tree/DirichletMultinomial

There are unit-tests 
There is a usermanual description

However, when estimating the theta parameter it was running to bounds so this needs furthur investigation

**Comment by NIWAFisheriesModelling** [comment]
Added TestModel "LIM_tc_Dm", the "LIM_tc" model with the Dirichlet multinomial likelihood used for the composition observations.

**Comment by Craig44** [comment]
I reviewed and updated most comments in recent Pull Request.

However the comment made here https://github.com/NIWAFisheriesModelling/CASAL2/pull/405#discussion_r965360406 would benefit from additional looking. The SSB has doubled vs the multinomial test case. Is this reasonable? @amart

**Comment by NIWAFisheriesModelling** [comment]
SSB in which test case model?

**Comment by NIWAFisheriesModelling** [comment]
The test cases were screwed around with, and not iteratively reweighted (as far as I recall).
Do we have a casal2 assessment that has been appropriately iteratively reweighted?

**Comment by Craig44** [comment]
Touche we may be comparing a weighted estimation (Dirichlet multinomial) with an unweighted estimation (multinomial with no stage two weightings). If you are happy with this you can close and merge.

**Comment by NIWAFisheriesModelling** [comment]
I might just run the multinomial one with a double or half EFS to check it does move the SSB estimates.
If SSB doesn't move much then it isnt this.

**Comment by NIWAFisheriesModelling** [comment]
For TestModel LIN_tc, on CentOS 7.9 with Casal2 compiled with devtoolset-11, the MPD B0 estimate is 308529. The composition data have sample sizes ranging from 13 to 120. Changing all of the sample sizes to 1/10 of their current value for the 5 sets of composition observations results in the MPD B0 estimate of 396892. Using the Dirichlet multinomial likelihood results in effective sample sizes of less than 5, most of which are less than 2.

**Comment by NIWAFisheriesModelling** [comment]
Merged pull request #405 on 2022-09-08.
