### ISSUE TITLE
Migrate betadiff casal flags_off into Testmodels before moving out of repo.

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#402]
For each model TestCase will want to freeze one version in the TestModel framework.

- this will require adding an @assert in each model for objective function

- update BuildSystem/classess/ModelRunner.py to run estimation.

**Comment by NIWAFisheriesModelling** [comment]
Use the betadiff_casal_flags_off version of the 7 TestCase models.

**Comment by NIWAFisheriesModelling** [comment]
Completed on 2022-08-29 in pull request #404 .
