### ISSUE TITLE
CategoryList report not compatiable with Casal2 R library function extract.mpd()

### ISSUE THREAD

**Issue by Craig44** [NIWAFisheriesModelling/CASAL2#406]
The Simple Example [here](https://github.com/NIWAFisheriesModelling/CASAL2/tree/master/Examples/Simple/config) model has a report type `category_list`. When I use `extract.mpd()` on the run.log and estimate.log I get an error. I have tracked the error to this report. This @report needs to be rewritten so that it is compatible with the R library extract function, or removed from the example config files.

The same for @report type `mpd` when estimating

**Comment by NIWAFisheriesModelling** [comment]
What information should be in the reports of type `category_list`? It is not described in the user manual.

**Comment by Craig44** [comment]
I am not sure could be a legacy report, I am not familiar with/never have used it. However, recently I was doing some training with the simple example model which errored out. Perhaps if there is no information on this report. Remove it and take it out of the example config files.

**Comment by NIWAFisheriesModelling** [comment]
I will remove the `category_list` report and fix the `mpd` report.

**Comment by Craig44** [comment]
It is worth noting the `mpd` report is used by `casal2 -M` and `-E` which I think is related to 
 the [MPD classs](https://github.com/NIWAFisheriesModelling/CASAL2/blob/master/CASAL2/source/MPD/MPD.cpp)

**Comment by NIWAFisheriesModelling** [comment]
Addressed in commits on 2022-09-09, e.g., commit [ed1376459bbab6601b30bed2ea3ffb4057ce6b3d](https://github.com/NIWAFisheriesModelling/CASAL2/commit/ed1376459bbab6601b30bed2ea3ffb4057ce6b3d).
