### ISSUE TITLE
CASAL2 length based : min_length max_length ?

### ISSUE THREAD

**Issue by fannyouzoulias** [NIWAFisheriesModelling/CASAL2#414]
Hello, 

I have been using CASAL2 (age based) for toothfish assessment in Kerguelen (I work with Félix Massiot-Granier in the French National Muséum of Natural History). 
I am now trying to use for assessment of rock lobster in Saint-Paul and Amsterdam, using the length-based version. 

I did not found any details on the manuel regarding the @model section in the population csl2 for a length-based model. When running the model (estimate mode) I have these error messages:
([ERROR] At line 6 in config/population.csl2: Parameter 'min_length' is not supported
[ERROR] At line 7 in config/population.csl2: Parameter 'max_length' is not supported
[FATAL_ERROR] At line 20 in config/population.csl2: The specified type (derived) is invalid for the command @initialisation_phase)

Here is my block @model in the population section. I specified the type = length and the min_length and max_length. 
min_length    1   
max_length     10
length_plus    True 
start_year  1987
final_year  2022
projection_final_year 2057
type length
base_weight_units tonnes
initialisation_phases phase1
time_steps Summer Winter AgeIncrement
length_bins 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18
age_plus False
threads 1 

Is there anything I do wrong in the code? How do you specify that you want a length-based model? 

Thank you very much in advance for your help, 

Fanny Ouzoulias

**Comment by Craig44** [comment]
Hi there,
See section 9 of the length based manual for more information [(see here)](https://github.com/NIWAFisheriesModelling/CASAL2/blob/master/Documentation/UserManual/CASAL2_Length.pdf).

There is no `min_length` or `max_length` command. I don't think you there is a minimum plus group although I may be mistaken. If you want max length plus group, you will need to specify `length plus true` and `length_plus_group 25`. A good resource for setting up a length-based models [can be found here](https://github.com/NIWAFisheriesModelling/CASAL2/tree/master/Examples/LengthBasedModel).

Hope that helps

**Comment by fannyouzoulias** [comment]
Hello, 

It helps a lot, thank you very much! It works now.
