### ISSUE TITLE
All minimisers need to return a co-variance matrix to use in MCMC

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#75]

**Comment by Craig44** [comment]
Do all minimisers return a covariance matrix? @Zaita if some don't we need to add business rules around stopping people running an mcmc with certain minimisers.

**Comment by alistairdunn1** [comment]
Some don't, for example de solver. . We need the business rule. 

On 15 July 2016 11:02:55 AM NZST, Craig Marsh <notifications@github.com> wrote:
>Do all minimisers return a covariance matrix? @Zaita if some don't we
>need to add business rules around stopping people running an mcmc with
>certain minimisers.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/NIWAFisheriesModelling/CASAL2/issues/75#issuecomment-232817343

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Craig44** [comment]
Find out what minimisers don't generate co-variance matrices and get them to print an error if the runmode is -m "you shouldn't use this minimiser as it wont generate a covariance and so your MCMC wont have a true proposal distribution"
