### ISSUE TITLE
@yield - yield run mode

### ISSUE THREAD

**Issue by Zaita** [NIWAFisheriesModelling/CASAL2#8]
Implement yield run mode

**Comment by Zaita** [comment]
NIWA needs to write a design specification for this. No information has been provided on what yield mode is, what it does and how it's suppose to behave.

**Comment by Craig44** [comment]
Can we move this to the R-library? Not many assessments that use Casal2 and CASAL actually derive yields. A suggestion for getting yields is to use R-functions to search for future U's and catches to solve for MSY and or other yield reference points.
